remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Nolan Burkhart
description: About Me
affiliation: High School Student
email: nolan.burkhart@gmail.com
logo: ./assets/avatar.png
